# Imports

In [ ]:
# face_recognition, cmake, dlib

In [2]:
import tensorflow.keras
from PIL import Image, ImageOps
import numpy as np
import pandas as pd
# import face_recognition
import cv2

# Set-Up Labels

In [3]:
labels = pd.read_csv('converted_keras/labels.txt', header = None)

labels = labels.rename(columns = {0:'Names'})
new_index = []
new_labels = []

for x in labels['Names']:
    new_index.append(int(x.split(" ", 1)[0]))  # to ensure it is not appended as a list
    new_labels.append(x.split(" ", 1)[1])
    
prediction_dict = dict(zip(new_index, new_labels))

# Code copied from Google 

In [4]:
# Disable scientific notation for clarity
np.set_printoptions(suppress=True)

# Load the model (set compile to False)
model = tensorflow.keras.models.load_model('converted_keras/keras_model.h5', compile = False)


In [6]:
# Create the array of the right shape to feed into the keras model
# The 'length' or number of images you can put into the array is
# determined by the first position in the shape tuple, in this case 1.
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

# Replace this with the path to your image
image = Image.open('img/test/grint_1.jpg')

#resize the image to a 224x224 with the same strategy as in TM2:
#resizing the image to be at least 224x224 and then cropping from the center
size = (224, 224)
image = ImageOps.fit(image, size, Image.ANTIALIAS)

#turn the image into a numpy array
image_array = np.asarray(image)

# display the resized image
# image.show()

# Normalize the image
normalized_image_array = (image_array.astype(np.float32) / 127.0) - 1

# Load the image into the array
data[0] = normalized_image_array

# run the inference
prediction = model.predict(data)
print(prediction)
print(prediction_dict[2])

[[0.13841462 0.8415454  0.0200399 ]]
Daniel Radcliffe


In [10]:
# This allows it to now return the name of the prediction

# Using Computer Vision

In [54]:
cap = cv2.VideoCapture(0)

In [55]:
success, img = cap.read()

In [56]:
cap.release()

In [57]:
res = cv2.resize(img, dsize=(224, 224), interpolation=cv2.INTER_CUBIC)
normalized_image_array = (res.astype(np.float32) / 127.0) - 1
data[0] = normalized_image_array
prediction = model.predict(data)
print(prediction)
print(prediction_dict[2])

[[0.14452581 0.5813541  0.27412015]]
Daniel Radcliffe


In [63]:
# cv2.imshow("Webcam",img)

In [64]:
# cv2.waitKey(1)

In [9]:
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True:
    success, img = cap.read()
    res = cv2.resize(img, dsize=(224, 224), interpolation=cv2.INTER_CUBIC)
    normalized_image_array = (res.astype(np.float32) / 127.0) - 1
    data[0] = normalized_image_array
    prediction = model.predict(data)
    print(prediction)
    print(prediction_dict[2])
    
    cv2.imshow("Webcam",img)
    cv2.waitKey(1)

[[0.00951035 0.9172767  0.073213  ]]
Daniel Radcliffe
[[0.04005071 0.8329365  0.12701271]]
Daniel Radcliffe
[[0.03147059 0.87761444 0.09091501]]
Daniel Radcliffe
[[0.03525032 0.8742131  0.09053658]]
Daniel Radcliffe
[[0.04802997 0.83042705 0.12154293]]
Daniel Radcliffe
[[0.05795386 0.80110383 0.14094235]]
Daniel Radcliffe
[[0.03519213 0.7723462  0.19246167]]
Daniel Radcliffe
[[0.0333266  0.6244317  0.34224167]]
Daniel Radcliffe
[[0.04816759 0.72259176 0.2292407 ]]
Daniel Radcliffe
[[0.07471374 0.6357946  0.2894917 ]]
Daniel Radcliffe
[[0.11941049 0.5047793  0.3758103 ]]
Daniel Radcliffe
[[0.11682076 0.60369146 0.27948773]]
Daniel Radcliffe
[[0.19810155 0.5417973  0.26010123]]
Daniel Radcliffe
[[0.148057   0.464964   0.38697898]]
Daniel Radcliffe
[[0.09270216 0.55312073 0.35417712]]
Daniel Radcliffe
[[0.05123777 0.6638167  0.28494558]]
Daniel Radcliffe
[[0.09089077 0.6034413  0.30566794]]
Daniel Radcliffe
[[0.12826756 0.5311652  0.34056732]]
Daniel Radcliffe
[[0.14383873 0.5724661  0.28

KeyboardInterrupt: 